
# List of additional cli arguments to configure kube-state-metrics
# for example: --enable-gzip-encoding, --log-file, etc.
# all the possible args can be found here: https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md
extraArgs:
 - '--metric-labels-allowlist=deployments=[*],pods=[*],nodes=[*],services=[*]'
